version: '3'

services:
  eureka:
      image: anapsix/alpine-java:8_jdk_unlimited
      ports:
        - '8761:8761'
      working_dir: /eureka-server
      volumes:
        - ./eureka-server:/eureka-server
      command: './gradlew bootRun'
      environment:
        - GRADLE_USER_HOME=cache
        - SPRING_PROFILES_ACTIVE=dev
  api-gateway:
      image: anapsix/alpine-java:8_jdk_unlimited
      ports:
        - '8080:8080'
      working_dir: /api-gateway
      volumes:
        - ./api-gateway:/api-gateway
      depends_on:
        - eureka
      command: './gradlew bootRun'
      environment:
        - GRADLE_USER_HOME=cache
        - SPRING_PROFILES_ACTIVE=dev
  users-api:
      image: anapsix/alpine-java:8_jdk_unlimited
      ports:
        - '8081:8081'
      working_dir: /users-api
      volumes:
        - ./users-api:/users-api
      depends_on:
        - eureka
        - postgresdev
      command: './gradlew bootRun'
      environment:
        - GRADLE_USER_HOME=cache
        - SPRING_PROFILES_ACTIVE=dev
  react:
        image: node
        ports:
          - '3000:3000'
        working_dir: /ui
        volumes:
          - ./ui:/ui
        command: 'npm start'
        environment:
          - GRADLE_USER_HOME=cache
          - SPRING_PROFILES_ACTIVE=dev
          - REACT_APP_USERS_API=http://localhost:8080
  postgresdev:
        image: postgres
        ports:
         - "5432:5432"
        environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=pgdev
  flyway-migrations:
      image: jimmyoak/flyway:4.0.3
      command: wait-for-it --timeout=30 --strict postgresdev:5432 -- flyway migrate
      volumes:
        - './flyway-migrations/conf:/flyway/conf'
        - './flyway-migrations/sql:/flyway/sql'
      depends_on:
        - postgresdev
